-- RE4-SOURCE-UNIT: config
--[[
RE4 HUB · CENTRAL CONFIG REGISTRY
Single source of truth for release identity, source artifact revisions and all
runtime-tunable parameters. This file is passive and has no Core/UI dependency.
Changing Config/Data/UI/Language artifacts does not require rebuilding main.lua.
]]
local Config = {
    Schema = 2,
    App = {
        Product = "Re4Hub",
        HubName = "RE4 HUB",
        Version = "2.3.15",
        Revision = "release-2.3.15-final-20260912.1",
        BuildName = "2.3.15-final",
        DisplayVersion = "2.3.15 Final",
        Channel = "stable",
        UpdatedAt = "2026-09-12",
    },
    Source = {
        Paths = {
            Main = "main.lua", Config = "config.lua", Data = "data.lua", UI = "ui.lua",
            HubInfo = "hub_info.json",
            LanguageBase = "language/", LanguageManifest = "language/manifest.json",
        },
        Artifacts = {
            Config = "config-2.3.15-final-20260912.1",
            Data = "game-data-2.3.15-final-20260912.1",
            UI = "ui-2.3.15-final-20260912.1",
            Language = "language-2.3.15-final-20260912.1",
        },
        Cache = { Prefix = "RE4Hub_2_3_15_Final_20260912_1_", Schema = 6 },
    },
    Runtime = {
        LegacyStep = 0.10,
        Cadence = {
            CooperativeYield = 0.0,
            Frame25ms = 0.025, Fast30ms = 0.03, Input40ms = 0.04, Fast50ms = 0.05, Fast60ms = 0.06,
            Fast80ms = 0.08, Input90ms = 0.09, Step100ms = 0.10, Step120ms = 0.12, Step150ms = 0.15,
            Step180ms = 0.18, Step200ms = 0.20, Step250ms = 0.25, Step300ms = 0.30, Step350ms = 0.35,
            Step400ms = 0.40, Step450ms = 0.45, Step500ms = 0.50, Step600ms = 0.60, Step700ms = 0.70,
            Step750ms = 0.75, OneSecond = 1.0, OneHalfSeconds = 1.5, TwoSeconds = 2.0, TwoHalfSeconds = 2.5,
            ThreeSeconds = 3.0, ThirtySeconds = 30.0,
        },
        Scheduler = {
            TickRate = 0.04,
            MinInterval = 0.03,
            DefaultInterval = 0.10,
            WarnCooldown = 5.0,
        },
        Lifecycle = {
            StartupOrder = { BerryIndex=10, BossTracker=20, TeleportDirectory=30, HubInfo=40 },
            ShutdownPriority = {
                Presentation=1000, RuntimeCore=900, FeatureCleanup=800, StartupServices=700, Movement=650,
                Ownership=-300, PublicCore=-500, PlayerState=-600, Http=-1900, Remote=-2000,
            },
        },
        FeatureRuntime = {
            WaitSliceMin = 0.01,
            WaitSliceMax = 0.10,
        },
        MovementCoordinator = {
            TickInterval = 0.04,
        },
        ManagedLegacy = {
            RetryDelay = 0.75,
            SafetyInterval = 0.50,
            SchedulerInterval = 0.10,
        },
        Watchdog = {
            Interval = 2.0,
        },
        Utilities = { RedeemInterval = 0.45 },
        AntiKick = {
            Interval = 18 * 60,
            InputHold = 1.0,
        },
        Presentation = {
            FarmStateDebounce = 0.25,
            FarmStateInterval = 0.80,
            ESPInterval = 0.50,
            StatusInterval = 0.50,
            DashboardInterval = 1.0,
            SlowStatusInterval = 1.0,
            LeviathanStatusInterval = 1.5,
        },
        FightingStyle = {
            OwnershipConfirmDelay = 0.35,
            ActionCooldown = 0.90, AutoInvokeCooldown = 4.0,
            ActionLeaseTTL = 18.0, MovementLeaseTTL = 18.0,
            TravelTouchTTL = 4.0, ActionTouchTTL = 3.0, InteractionTouchTTL = 5.0,
            DirectVerifyTimeout = 1.35, DealerVerifyTimeout = 2.8,
            DealerFailureTTL = 1.0,
            DealerActionTimeout = 1.2,
            DealerResolveTimeout = 2.5,
            DealerTweenTimeoutMin = 8.0, DealerTweenTimeoutMax = 140.0, DealerTweenTimeoutExtra = 12.0,
            OwnershipProbeInterval = 0.45,
            AutoSchedulerInterval = 1.25,
            ProgressRefreshInterval = 5.0,
            StoreConfirmTimeout = 1.2,
            LegacyFlags = {
                DarkStep="AutoStyleDarkStep", Electric="AutoStyleElectric", WaterKungFu="AutoStyleWater",
                DragonBreath="AutoStyleDragonBreath", Superhuman="Auto_SuperHuman", DeathStep="AutoDeathStep",
                Sharkman="Auto_SharkMan_Karate", ElectricClaw="Auto_Electric_Claw", DragonTalon="AutoDragonTalon",
                Godhuman="Auto_God_Human", Sanguine="Snaguine",
            },
        },
        BossObtain = {
            HitSettleDelay = 0.05, MinimumDamageShareDefault = 0.10, WatchTimeout = 3.5,
            ApproachWait = 0.10,
            MissingBossWait = 2.0,
            ApproachHeight = 20,
            ArrivalRadius = 30,
            MovementPriority = 58,
        },
        Farm = { ChestStopItemInterval = 0.25 },
        QuestState = { TitleConfidenceMin = 10 },
        RaceProgression = {
            StatePollInterval = 0.45,
            ActionCooldown = 0.75,
            InteractionRadius = 14,
            FlowerArrivalRadius = 5,
        },
        FeatureTiming = {
            BootstrapCharacterReadyTimeout = 8.0, InstanceResolveTimeout = 5.0,
            FactionSwitchMinDelay = 0.45, FactionStableWindow = 0.12,
            FarmQuestAbandonCooldown = 0.75, FarmQuestStartCooldown = 0.75,
            QuestRootScanInterval = 0.25, QuestTitleScanInterval = 1.0,
            SaberButtonVerifyTimeout = 1.25,
            FightingStyleDealerResolveTimeout = 2.5, FightingStyleOwnershipProbeInterval = 0.45,
            BringEntryStaleTTL = 1.25,
            TushitaSkillRouteTimeout = 12.0,
            BuddhaEquipTimeout = 0.8,
            MasterySwordLoadInterval = 1.5,
            FishingAutoSellInterval = 8.0,
            FishingSkillInterval = 1.0,
            SecondSeaDetectiveInterval = 0.55,
            SecondSeaCaptainInterval = 0.85, SecondSeaProgressCacheTTL = 0.45,
            ThirdSeaProgressCacheTTL = 0.45, ThirdSeaActionInterval = 0.75,
            ThirdSeaFruitActionInterval = 0.75, ThirdSeaTravelInterval = 1.0,
            GachaResolveBackoff = 3.0,
            FruitInventoryProbeInterval = 1.0,
            FruitStoreConfirmTimeout = 1.2,
            FruitGachaHardTimeout = 35.0,
            PvPTargetFreshTTL = 1.0,
            SeaQuestCooldown = 15 * 60,
        },
        Team = {
            WaitTimeout = 1.0, RemoteConfirmTimeout = 0.75, RemoteAttempts = 2, UIResolveTimeout = 2.5,
        },
        ServerNavigator = {
            BrowserMaxPages = 5, HttpMaxPages = 3, DefaultCapacity = 12, MaxCandidates = 20, JobIdMinLength = 8,
            TravelCancelGrace = 0.25,
        },
        ActionManager = {
            DefaultTTL = 12.0, DefaultPriority = 0, MinTTL = 1.0,
            RaidLeaseTTL = 2.5, RaidPriority = 100,
            FarmLeaseTTL = 2.0, FarmPriority = 70,
            MasteryLeaseTTL = 3.0, MasteryPriority = 60,
            BuddhaEquipmentTTL = 1.5, BuddhaEquipmentPriority = 30,
            FruitEquipmentTTL = 2.5, FruitEquipmentPriority = 120,
        },
        QueryCache = {
            DefaultTTL = 1.0,
        },
        BossTracker = {
            DefeatedHistoryTTL = 5.0,
            DefaultPhaseGrace = 0.18, RecentlyLiveGrace = 2.5,
            FishmanLordPhaseGrace = 1.75,
            DefaultStreamingTargetRadius = 1024,
            MinStreamingConfidenceRadius = 450, MaxStreamingConfidenceRadius = 2200, StreamingConfidenceScale = 0.70,
        },
        Remote = {
            WarnCooldown = 5.0,
        },
        Diagnostics = {
            -- Event-driven transport observability only; no polling/background worker.
            Travel = { Enabled = true, HistoryLimit = 48, DedupWindow = 1.0 },
        },
        Cache = {
            DefaultTTL = 5.0,
            MaterialTTL = 2.5,
            WeaponTTL = 6.0,
            LegacyTTL = 2.5,
            BonesTTL = 1.5,
            InventoryFruitsTTL = 6.0,
            FruitsTTL = 15.0,
            ItemReplicationTTL = 10.0,
            UnlockablesTTL = 6.0,
        },
        CombatPulse = {
            TTL = 0.45,
            MinTTL = 0.15,
        },
        SpinPosition = {
            MinTTL = 0.25,
            DefaultTTL = 0.75,
            RefreshTTL = 0.65,
            SchedulerInterval = 0.20,
        },
        KillAura = {
            Interval = 2.0,
            Range = 500,
        },
        MovementSupport = {
            SafetyInterval = 0.50,
            RefreshInterval = 0.05,
        },
        Ownership = {
            RefreshInterval = 5.0,
            StyleRefreshInterval = 120.0,
            ControlSafetyInterval = 15.0,
            ItemsSchedulerInterval = 1.0,
        },
        ServerHop = {
            CheckInterval = 1.0,
            AutoHopInterval = 1800.0,
        },
        Raid = {
            LifecycleInterval = 0.10, StartInteractionRadius = 18,
            -- RaidTimer is a UI signal, not authoritative completion. This short
            -- grace only absorbs HUD handoff/flicker before native finalization.
            EndUiGrace = 0.85,
            -- Bounded observation window for reward + native server relocation.
            -- No forced success/teleport is performed when reward is unconfirmed.
            NativeFinalizeTimeout = 12.0,
            ChipConfirmTimeout = 3.0,
            LawChipConfirmTimeout = 3.0,
            LawStartConfirmTimeout = 8.0,
            RaidStartConfirmTimeout = 8.0,
            NotificationCooldown = 5.0,
            DefaultBasicRaid = "Ice",
            ChipWorkerSafetyInterval = 15.0,
            IslandHoldArrivalRadius = 10,
            BasicChipBeliCost = 100000,
            AdvancedChipFragmentCost = 1000,
            -- This cooldown is scheduled only after a Beli purchase that this runtime
            -- actually confirmed; ambiguous transactions are fail-closed, never retried.
            BeliCooldown = 7200.0,
        },
    },

    Movement = {
        -- Post-update player movement baseline. Keep this conservative; mob movement is separate.
        Interaction = {
            Touch = { MinArrivalRadius = 0.65, MaxArrivalRadius = 1.8, GeometryScale = 0.18 },
            TargetNoProgressTimeout = 5.0, MinProgressDistance = 0.75,
        },
        RequestProfiles = {
            ["barista_cousin"] = { Priority = 55 },
            ["bisento_v2_greybeard"] = { Priority = 56, ArrivalRadius = 32, Height = 22 },
            ["bones"] = { Priority = 50 },
            ["boss_approach"] = { Priority = 58, ArrivalRadius = 32, Height = 22 },
            ["cake_island"] = { Priority = 50 },
            ["cake_mobs"] = { Priority = 50 },
            ["cake_prince_approach"] = { Priority = 56, ArrivalRadius = 32, Height = 22 },
            ["cake_spawn"] = { Priority = 50 },
            ["chest"] = { InteractionMode = "Touch" },
            ["combat"] = { ArrivalRadius = 8 },
            ["dough_cake_mobs"] = { Priority = 50 },
            ["dough_cocoa"] = { Priority = 50 },
            ["dough_hop_approach"] = { Priority = 54, ArrivalRadius = 35, Height = 26 },
            ["dough_hop_target"] = { Priority = 52 },
            ["dough_king_approach"] = { Priority = 56, ArrivalRadius = 32, Height = 22 },
            ["dough_red_door"] = { Priority = 55, ArrivalRadius = 8 },
            ["dough_unlock_boss"] = { Priority = 56, ArrivalRadius = 32, Height = 22 },
            ["dough_unlock_cocoa"] = { Priority = 50 },
            ["dungeon_combat"] = { ArrivalRadius = 8 },
            ["ectoplasm_wait"] = { Priority = 45, ArrivalRadius = 40 },
            ["elite"] = { Priority = 52 },
            ["elite_approach"] = { Priority = 54, ArrivalRadius = 35, Height = 28 },
            ["farm_island"] = { Priority = 20, ArrivalRadius = 24 },
            ["farm_level_quest"] = { ArrivalRadius = 8 },
            ["farm_level_quest_bootstrap"] = { ArrivalRadius = 24 },
            ["fruit_world"] = { Priority = 48, ArrivalRadius = 4 },
            ["legacy_callsite"] = { Priority = 35 },
            ["legacy_teleport"] = { Priority = 35 },
            ["fighting_style"] = { Priority = 70, ArrivalRadius = 14 },
            ["gravestone"] = { Priority = 48, ArrivalRadius = 8 },
            ["law_raid"] = { Priority = 84, ArrivalRadius = 30, Height = 18 },
            ["manual_special_region"] = { Priority = 70 },
            ["mastery_fruit"] = { ArrivalRadius = 8 },
            ["mastery_gun"] = { ArrivalRadius = 8 },
            ["mastery_sword"] = { ArrivalRadius = 8 },
            ["mastery_weaken"] = { ArrivalRadius = 8 },
            ["material"] = { Priority = 48 },
            ["panic_escape"] = { Priority = 95 },
            ["phoenix_scientist"] = { Priority = 50, ArrivalRadius = 10 },
            ["pole_v1"] = { Priority = 58, ArrivalRadius = 30, Height = 20 },
            ["pvp_target"] = { Priority = 68, ArrivalRadius = 10 },
            ["raid_island"] = { Priority = 90 },
            ["raid_island_hold"] = { Priority = 90 },
            ["raid_next_island"] = { Priority = 90 },
            ["raid_start"] = { Priority = 85, ArrivalRadius = 12 },
            ["raid_wait_hold"] = { Priority = 90 },
            ["saber_button_"] = { Priority = 55, ArrivalRadius = 2.5 },
            ["saber_desert"] = { Priority = 55, ArrivalRadius = 7 },
            ["saber_expert"] = { Priority = 55, ArrivalRadius = 26, Height = 18 },
            ["saber_mob_leader"] = { Priority = 55, ArrivalRadius = 26, Height = 18 },
            ["saber_relic_gate"] = { Priority = 55, ArrivalRadius = 4 },
            ["saber_torch"] = { Priority = 55, ArrivalRadius = 7 },
            ["saber_torch_bootstrap"] = { Priority = 55, ArrivalRadius = 24 },
            ["second_sea_door"] = { Priority = 58, ArrivalRadius = 2.5 },
            ["second_sea_door_bootstrap"] = { Priority = 55, ArrivalRadius = 35 },
            ["second_sea_ice_admiral"] = { Priority = 58, ArrivalRadius = 28, Height = 18 },
            ["skull_guitar_ectoplasm"] = { Priority = 45, ArrivalRadius = 40 },
            ["soul_reaper_approach"] = { Priority = 56, ArrivalRadius = 32, Height = 22 },
            ["soul_reaper_summon"] = { Priority = 52, ArrivalRadius = 8 },
            ["tyrant_approach"] = { Priority = 56, ArrivalRadius = 34, Height = 24 },
            ["tyrant_area"] = { Priority = 50 },
            ["tyrant_summon_point"] = { Priority = 52, ArrivalRadius = 5 },
        },
        Thresholds = {
            Physics = { VelocityStopEpsilon = 0.05, StableVelocityMax = 80 },
            Combat = { AutoClickRange = 35, SpinRepositionEpsilon = 1, TargetLockAnchorEpsilon = 3 },
            Bypass = { SpawnMatchRadius = 1800 },
            RoutePlanner = { DirectionEpsilon = 1 },
            TravelResolver = { DynamicTargetEpsilon = 1 },
            Farm = { QuestAnchorRadius = 8, PirateRaidDetectionRadius = 500, PirateRaidTargetRadius = 2000, BerryInteractionRadius = 10 },
            Haunted = { PhoenixScientistRadius = 12, SoulReaperSummonRadius = 10, GravestoneRadius = 10 },
            Tyrant = { SummonApproachRadius = 6, SkillUseRadius = 7 },
            Tushita = { TorchArrivalRadius = 10, SealedKatanaFarRadius = 20 },
            CDK = { DimensionRadius = 1000, TorchRadius = 5, DimensionMobRadius = 300, SoulReaperSummonRadius = 8, BoatArrivalRadius = 3, BoatInteractRadius = 10 },
            Saber = { ButtonInteractRadius = 4, FinalInteractRadius = 10 },
            Bartilo = { QuestApproachRadius = 20, QuestInteractRadius = 1, MazeArrivalRadius = 1 },
            Citizen = { QuestApproachRadius = 30, QuestInteractRadius = 4 },
            FightingStyle = { DealerArrivalRadius = 14 },
            Boat = { PurchaseRadius = 10, EventArrivalRadius = 10 },
            Race = { FishTrialRadius = 1500, TrialEnemyRadius = 250, DragonBeltRadius = 50, BambooRadius = 200, DragonWizardFarRadius = 300, UzothInteractRadius = 25 },
            SeaEvent = { PrehistoricFarRadius = 2000 },
        },
        Offsets = {
            Combat = {
                RandomOrbitRadius = 25,
                SeaBehind = 8,
                SeaFruitHeight = 10,
                SeaDefaultHeight = 50,
                FruitHeightCap = 20,
                DefaultHeight = 30,
                FruitYawDegrees = 90,
                DefaultYawDegrees = 180,
                BossApproach = {0,30,0},
                BossApproachHigh = {0,22,0},
                PvPFallback = {0,8,4},
                PvPSkypiea = {0,8,0},
                PvPSkypieaPitchDegrees = -45,
                PvPDefeatBehind = {0,0,15},
                ObservationActive = {3,0,0},
                ObservationIdle = {0,50,0},
            },
            Raid = { IslandHover = {0,60,0} },
            Safety = { PanicEscape = {0,500,0} },
            NPC = { Interact = {0,0,6}, Bootstrap = {0,20,0}, DealerInteract = {0,0,5} },
            Item = { CombatAbove = {0,20,0}, Pickup = {0,1,10}, SpawnPull = {0,0,-2} },
            Boat = {
                Seat = {0,1,0}, ZoneHigh = {0,150,0}, FishBoat = {0,-50,-25},
                PirateBrigade = {0,-30,-10}, PirateGrandBrigade = {0,-50,-50},
            },
            Mirage = { CenterHigh = {0,300,0}, GearHigh = {0,400,0} },
            Trial = { MinkBelow = {0,-20,0}, CyborgAbove = {0,500,0}, FishmanWaterHeight = 300 },
            Dragon = { BambooSide = {4,0,0} },
            Kitsune = { IslandHigh = {0,500,0}, Shrine = {0,2,0} },
            Manual = { IslandHover = {0,30,0}, FollowPlayer = {0,0,7}, NPC = {0,0,6} },
            Fishing = { RayOrigin = {0,10,0}, RayDirection = {0,-500,0} },
            BossTracker = { DefaultApproachHeight = 18 },
            NPCTravel = { ExactPriority = 58, ExactArrivalRadius = 10, BootstrapPriority = 55, BootstrapArrivalRadius = 45 },
            AtomicLocal = { ArrivalRadius = 3 },
            RoutePlanner = { DefaultHorizontalDirection = {1,0,0} },
            SeaEvent = { WaterApproachHeight = 200 },
            FruitRain = { SpawnHorizontalRadius = 50, SpawnHeight = 100 },
            Saber = { DoorPadding = 2.5, DefaultSide = {0,0,1} },
        },
        Physics = { BodyVelocityMaxForce = {1e9,1e9,1e9} },
        WalkWater = { PlaneSize = {1000,112,1000} },
        TweenSpeed = 170,
        PlayerFollowerDistance = 200,
        PlayerCorrection = {
            Enabled = true,
            RebaseGap = 9,
            MinRebaseGap = 6,
            BehindTargetTolerance = 5,
            Debounce = 0.18,
            -- Ignore one-frame server corrections; only rebase when the same
            -- behind-the-block condition persists briefly.
            ConfirmTime = 0.08,
        },
        BypassTP = {
            DefaultEnabled = true,
            MinDistance = 3500,
            MinDistanceGain = 650,
            -- Runtime PlayerSpawns are the transport authority. Destination island
            -- labels remain semantic routing data and are never a destructive-spawn gate.
            DestinationIslandRadius = 2800,
            DestinationStrongRadius = 900,
            DestinationAmbiguityMargin = 650,
            -- Cr4-compatible generalized spawn policy: do not respawn into the
            -- current runtime spawn group, and consider only bounded useful hops.
            SpawnClusterRadius = 2500,
            MaxCandidateDistance = 10000,
            -- Wrong-respawn suppression is bounded and tied to route+checkpoint state,
            -- so stale failures cannot permanently disable Bypass.
            FailureStateTTL = 12.0,
            VerifyTimeout = 5.0,
            VerifyStep = 0.08,
            IntentionalRespawnGrace = 2.0,
            MinVerifyTimeout = 1.0, MinFailureStateTTL = 1.0,
        },
        TransitionAwareness = {
            Enabled = true,
            SegmentEdgeEpsilon = 0.005,
            ExternalRelocationDistance = 200,
            EventDebounce = 0.20,
            HazardRadius = 160,
            MinHazardRadius = 40,
            HazardMargin = 100,
            MaxHazards = 12, MinHazards = 1,
            MaxReplansPerRequest = 2,
        },
        Bring = {
            ScanInterval = 0.22, SweepInterval = 0.75,
            -- Conservative Bring envelope limits cross-floor/cross-room followers on compact vertical maps.
            -- Cadence, MaxMob and movement mechanics remain unchanged.
            Range = 350,
            Speed = 300,
            MinRange = 20,
            CorrectionFloor = 3,
            -- Shared per-mob origin leash. A mob is never deliberately moved
            -- farther than this from its first observed runtime position.
            FollowerDistance = 200,
            MaxMob = 6, SimulationRadiusInterval = 1.0,
        },
        Controller = {
            ExternalRelocationMinGap = 50, MinArrivalRadius = 3, CombatOwnerPriority = 100, DefaultIslandBypassRadius = 1800, MinIslandBypassRadius = 250,
            PositionSnapRadius = 1, HoldRadiusMultiplier = 4, HoldRadiusFloor = 40,
            DefaultWaitTimeout = 8, TweenTimeoutMin = 3, TweenTimeoutExtra = 4, SegmentTweenTimeoutExtra = 12, SpecialGatewayArrivalRadius = 10,
            DynamicTargetRefreshFloor = 6, DynamicTargetRefreshRadiusScale = 0.5,
            TweenRecoveryAttempts = 1, StallWindowFloor = 2.5, StallRecoveryWindowMultiplier = 3,
            DefaultPriority = 10,
        },
        Raid = {
            IslandRadius = 750, LocalMarkerMargin = 100, EnemyMargin = 100, CurrentMargin = 120,
            NativeReturnMargin = 150, InRaidMarkerMargin = 160,
        },
        BossTracker = { Priority = 56, ArrivalRadius = 35 },
        CombatTargetLock = {
            StaleTTL = 1.35,
            BringInterval = 0.12,
            RefillInterval = 0.25,
            SweepInterval = 0.75,
        },
        TravelResolver = {
            ArrivalRadius = 10,
            LocalDirectDistance = 900,
            SpecialTimeout = 12,
            MaxTweenTimeout = 220,
            RecoveryWindow = 0.85,
            RootProgressEpsilon = 0.8,
            BlockProgressEpsilon = 0.35,
            -- TargetRevision refreshes a running local tween. RouteRevision is
            -- separate and only re-enters Portal/Bypass planning for a meaningful
            -- strategic destination change.
            StrategicRouteReplanDistance = 45,
            DynamicTargetRefreshDistance = 18,
            DynamicRouteReplanDistance = 650,
            TweenTargetEpsilon = 2,
            -- A satisfied combat hold owns position slightly beyond the arrival
            -- radius so ordinary replication jitter cannot release Noclip between
            -- combat ticks and restart the same vertical movement.
            HoldRadius = 20,
            -- Re-plan strategic transport after each verified hop. This keeps
            -- Bypass/portal chains inside one owner/session instead of forcing a
            -- long final Tween after the first useful relocation.
            MaxTransportHops = 4,
        },
        ManualTravel = {
            -- Direct user travel is authoritative over background Farm/Combat movement.
            -- The coordinator still owns cancellation/handoff; no feature is stopped.
            Priority = 150,
            OverrideActiveMovement = true,
            UpdateInterval = 0.08,
            ArrivalRadius = 8,
        },
        FastTravel = {
            DefaultEnabled = true,
            -- Native portal metadata describes capability/geometry only. Strategic
            -- selection is centralized in RoutePlanner where Bypass, Fast Travel and
            -- direct Tween compete from the current runtime state.
            NativeDestinationMatchRadius = 2200,
            -- Route-cost estimate uses Movement.TweenSpeed as the single speed source.
            -- No service-radius cutoff: every compatible portal competes by total
            -- Current->Entry + activation + Arrival->Destination cost.
            EntranceOverhead = 0.55,
            MinTimeGain = 0.85,
            ArrivalRadius = 650,
            MinCandidateArrivalRadius = 20, StrongCandidateArrivalRadius = 900,
            VerifyTimeout = 1.35, MinVerifyTimeout = 0.50,
            VerifyStep = 0.05,
            -- Re4.zip reference behavior: a portal is also confirmed by a real
            -- server relocation that materially improves the route, even when the
            -- landing point is offset from the registry arrival anchor.
            MinObservedMove = 120,
            MinObservedGain = 80,
        },
    },

    Combat = {
        TargetCacheInterval = 0.12,
        Mastery = {
            CooldownScaleEpsilon = 0.001,
            DefaultThresholdPercent = 35, MinThresholdPercent = 10, MaxThresholdPercent = 90, ThresholdStep = 5,
            DefaultRequirement = 600, QuestPriority = 60, QuestArrivalRadius = 8, QuestBootstrapArrivalRadius = 24,
            TargetFruitHeight = 10, TargetDefaultHeight = 30, TargetBehind = 8,
            SkillDefaults = {
                fruit = { Z=true, X=true, C=true, V=true, F=true },
                gun = { Z=true, X=true, C=true, V=true },
            },
        },
        Scheduler = { ActiveMastery = 0.07 },
        SilentAim = {
            PredictionAmount = 0.10,
            MaxRange = 1000,
            MinPredictionWalkSpeed = 5,
            AutoKenInterval = 0.10,
        },
        FastAttack = {
            AttackDistance = 65,
            BuddhaDistance = 999,
            -- Send cadence remains frame-bounded by the single RunService.Stepped owner.
            -- 0.01 is therefore a floor, not a request to create a faster background loop.
            AttackCooldown = 0.01,
            ComboResetTime = 0.30,
            MaxCombo = 4,
            -- Normal Melee/Sword FastAttack already uses RegisterAttack/RegisterHit and
            -- does not depend on the local attack animation finishing. Busy remains a
            -- hard gate for Fruit/Gun and mastery skill owners, where it represents
            -- real local action readiness rather than cosmetic M1 animation state.
            IgnoreBusyForRemoteMelee = true,
            ConfigRefreshInterval = 0.20,
            ConnectionSyncInterval = 0.10,
            FallbackToolCooldown = 0.30, MinToolCooldown = 0.05, BridgeRefreshInterval = 1.0,
        },
        PvP = {
            EnableRetryInterval = 1.25,
            EnableConfirmTimeout = 2.50,
            EnableConfirmStep = 0.08,
            TemporaryBlacklistTTL = 0.75,
            PvPDisabledBlacklistTTL = 4.0,
            ProtectionBlacklistTTL = 2.5,
            NoDamageBlacklistTTL = 4.0,
            NoDamageTimeout = 3.25,
            DamageProbeRange = 32,
            DamageEpsilon = 0.05,
            MinAttackWindows = 14,
            BlacklistMinTTL = 0.10,
            AccessoryMinimumBountyHonor = 250000, FallbackClickInterval = 0.16,
            SpinLeaseTTL = 0.55, CombatPulseTTL = 0.65, ApproachHeight = 10, ApproachBehind = 3,
        },
    },

    Visual = {
        BerryESPStudsOffset = {0,2.5,0},
        LowCpu = { ExplosionPressure = 1, ExplosionRadius = 1, FogEnd = 9e9, Brightness = 0, TextureId = 10385902758728957 },
        TweenAnchorSize = {1,1,1},
        RuntimeLight = { Range = 15, Color = {217,145,57} },
        MaxZoomDistance = 100000,
        Fullbright = { Ambient = {1,1,1}, ColorShiftBottom = {1,1,1}, ColorShiftTop = {1,1,1} },
        HazardLighting = { Ambient = {33,33,33}, Brightness = 0.3, FogEnd = 999 },
        IceWalk = {
            MinHorizontalSize = 13, MaxHorizontalSize = 15, Height = 1.7,
            SpawnY = -3.8, ShrinkSize = {0,0.3,0}, TweenDuration = 2.0,
            PitchJitter = 0.06, YawRange = 7, RollJitter = 0.07,
        },
    },

    Berry = {
        StepInterval = 0.12,
        PromptCooldown = 0.55,
        CollectConfirmTimeout = 1.00,
        EmptyStableWindow = 0.85,
        ArrivalRadius = 7,
        Priority = 5,
    },

    Fruit = {
        GachaCooldown = 2 * 60 * 60,
        StoreEquipConfirmTimeout = 0.90,
        CollectStepInterval = 0.10,
        CollectRetryInterval = 0.25,
        IdleScanInterval = 0.40,
        TweenStepInterval = 0.12,
        TweenIdleInterval = 0.40,
        TweenArrivalRadius = 4.0,
        ShopRefreshInterval = 15.0,
        ShopTransactionTTL = 4.0,
        ShopTransactionPriority = 115,
        ShopConfirmTimeout = 2.5,
        ShopConfirmStep = 0.10,
        GachaCloseTimeout = 25, GachaPresentationAppearTimeout = 3, GachaRetryDelay = 5, GachaLevelRetryDelay = 15,
        GachaStateCacheTTL = 3.0,
        MinRetryDelay = 1, GachaBlockedRetryDelay = 15,
    },

    SeaEvent = {
        BoatCollisionInterval = 0.35, SkillRange = 500, BoatInteractionRadius = 150,
        PrehistoricActivationRadius = 150, PrehistoricVFXRadius = 150,
        BoatBoost = { MaxSpeed = 350, Torque = 0.2, TurnSpeed = 5 },
    },

    Fishing = {
        StepInterval = 0.10,
        DefaultMaxLaunchDistance = 80,
        RodRequestInterval = 1.00,
        RodEquipConfirmTimeout = 1.00,
        BaitActionInterval = 0.80,
        BaitSelectConfirmTimeout = 1.25,
        BaitLowStockThreshold = 2,
        BaitTargetStock = 10,
        BaitMaxStack = 99,
        BaitMaxCraftBatchesPerCycle = 3,
        CraftSettleDelay = 0.20,
        CraftConfirmTimeout = 1.60,
        CraftConfirmStep = 0.40,
        CraftFailureRetryDelay = 2.50,
        CastChargeDelay = 0.70,
        CastConfirmTimeout = 1.50,
        CastRetryDelay = 0.35,
        CatchStartDelay = 0.25,
        CatchPulseInterval = 0.08,
        CatchTimeout = 15.0,
        QuestIdleInterval = 0.35,
        WaterSurfaceClearance = 2, DefaultTargetRadius = 18, DefaultBaitBundle = 10,
        DefaultQuestMinLevel = 20, QuestSuccessCooldown = 15, QuestFailureCooldown = 5,
    },

    Features = {
        Persistence = {
            Schema = 1,
            File = "RE4Hub_User_Config.json",
            -- Stable semantic exclusions only. Runtime state is never stored here.
            ExcludePrefixes = {"toggle.fighting.style.use.","toggle.teleport.to."},
        },
        Defaults = {
            ["toggle.anti.kick"] = true,
            ["toggle.stats.auto_melee"] = false,
            ["toggle.stats.auto_sword"] = false,
            ["toggle.stats.auto_gun"] = false,
            ["toggle.stats.auto_blox_fruit"] = false,
            ["toggle.stats.auto_defense"] = false,
            ["toggle.auto.get.law.sword"] = false,
            ["toggle.auto.get.pole.v1"] = false,
            ["toggle.auto.look.at.moon"] = false,
            ["toggle.auto.pole.v2"] = false,
            ["toggle.auto.quest.sea.2"] = false,
            ["toggle.auto.start.raid"] = false,
            ["toggle.auto.teleport.barista.cousin"] = false,
            ["toggle.auto.turn.on.haki"] = true,
            ["toggle.auto.turn.on.spin.position"] = false,
            ["toggle.auto.use.skill.z.buddha"] = false,
            ["toggle.disable.chat"] = false,
            ["toggle.disable.leader.board"] = false,
            ["toggle.disable.notify"] = false,
            ["toggle.fast.attack"] = true,
            ["toggle.fullbright"] = false,
            ["toggle.noclip"] = false,
            ["toggle.remove.hit"] = false,
            ["toggle.remove.lava"] = false,
            ["toggle.silent.aim"] = false,
            ["toggle.stop.item"] = true,
            ["toggle.turn.on.walk.on.water"] = true,
            ["toggle.auto.train.v4"] = false,
            ["toggle.auto.tween.to.advanced.fruit.dealer"] = false,
            ["toggle.auto.get.buddy.sword"] = false,
            ["toggle.auto.get.midnight.blade"] = false,
            ["toggle.auto.draco.v2"] = false,
            ["toggle.auto.hop.every.30.minutes"] = false,
            ["toggle.auto.haki.observation.v2"] = false,
            ["toggle.auto.get.lei.accessory"] = false,
            ["toggle.auto.farm.materials.skull.guitar"] = false,
            ["toggle.auto.farm.rip.indra"] = false,
            ["toggle.auto.get.serpent.bow"] = false,
            ["toggle.auto.get.dragon.trident"] = false,
            ["toggle.auto.three.color.haki"] = false,
            ["toggle.auto.quest.sea.3"] = false,
            ["toggle.auto.get.florentino.sword"] = false,
            ["toggle.auto.farm.darkbeard"] = false,
            ["toggle.auto.unlock.donswan"] = false,
            ["toggle.auto.race.v2"] = false,
            ["toggle.auto.race.v3"] = false,
            ["toggle.auto.get.ghoul.race"] = false,
            ["toggle.auto.get.cyborg.race"] = false,
            ["toggle.auto.haki.rainbow"] = false,
            ["toggle.auto.get.skull.guitar"] = false,
            ["toggle.auto.get.swan.glasses"] = false,
            ["toggle.auto.get.tushita"] = false,
            ["toggle.auto.get.yama"] = false,
            ["toggle.auto.find.kitsune.island"] = false,
            ["toggle.auto.complete.quest.bartilo"] = false,
            ["toggle.auto.get.black.spikey"] = false,
            ["toggle.swap.draco.race"] = false,
            ["toggle.turn.on.bypass.teleport"] = true,
            ["toggle.turn.on.fast.travel"] = true,
            ["toggle.auto.get.cdk"] = false,
            ["toggle.auto.quest.tushita.cdk"] = false,
            ["toggle.auto.quest.yama.cdk"] = false,
            ["toggle.auto.complete.quest.citizen"] = false,
            ["toggle.auto.collect.azure.ember"] = false,
            ["toggle.auto.complete.trial.race"] = false,
            ["toggle.auto.craft.volcanic.magnet"] = false,
            ["toggle.upgrade.dragon.talon.v3"] = false,
            ["toggle.auto.dark.blade.v3"] = false,
            ["toggle.auto.kill.player.after.trial"] = false,
            ["toggle.auto.dojo.trainer"] = false,
            ["toggle.auto.draco.v1"] = false,
            ["toggle.auto.draco.v3"] = false,
            ["toggle.auto.farm.training.dummy"] = false,
            ["toggle.auto.dragon.hunter"] = false,
            ["toggle.auto.collect.mirage.chest"] = false,
            ["toggle.auto.find.mirage.island"] = false,
            ["toggle.auto.teleport.frozen.dimension"] = false,
            ["toggle.get.quest.haki.rainbow"] = false,
            ["toggle.tween.to.mirage.island"] = false,
            ["toggle.auto.get.rengoku.sword"] = false,
            ["toggle.auto.get.key.rengoku"] = false,
            ["toggle.auto.attack.leviathan"] = false,
            ["toggle.auto.get.long.sword"] = false,
            ["toggle.auto.pull.lever"] = false,
            ["toggle.auto.collect.bones"] = false,
            ["toggle.auto.turn.on.v3"] = false,
            ["toggle.auto.turn.on.v4"] = false,
            ["toggle.auto.relic.draco.trial.v4"] = false,
            ["toggle.auto.reset.when.complete"] = false,
            ["toggle.panic.mode"] = false,
            ["toggle.auto.drive.to.hydra.island"] = false,
            ["toggle.auto.teleport.to.race.doors"] = false,
            ["toggle.auto.collect.gear"] = false,
            ["toggle.tween.to.draco.trial.v4"] = false,
            ["toggle.tween.to.legendary.sword.seller.npc"] = false,
            ["toggle.auto.trade.azure.ember"] = false,
            ["toggle.auto.train.draco.v4"] = false,
            ["toggle.auto.get.twin.hooks"] = false,
            ["toggle.tween.to.upgrade.draco.trial"] = false,
            ["toggle.turn.on.ice.walk"] = false,
            ["toggle.change.transparency.can.see"] = false,
            ["toggle.turn.on.time"] = false,
            ["toggle.auto.farm.haki.observation"] = false,
            ["toggle.auto.shrine.actived"] = false,
            ["toggle.auto.awakening"] = false,
            ["toggle.auto.attack.fish.boat"] = false,
            ["toggle.auto.attack.haunted.crew.member"] = false,
            ["toggle.kill.aura"] = false,
            ["toggle.auto.attack.fish.crew.member"] = false,
            ["toggle.auto.attack.pirate.ship"] = false,
            ["toggle.auto.kill.piranha"] = false,
            ["toggle.auto.collect.dragon.egg"] = false,
            ["toggle.auto.find.prehistoric.island"] = false,
            ["toggle.auto.start.event"] = false,
            ["toggle.auto.raid.safe"] = false,
            ["toggle.auto.sail.sit.down.and.turn.on"] = false,
            ["toggle.auto.attack.sea.beast"] = false,
            ["toggle.auto.kill.shark"] = false,
            ["toggle.auto.kill.terror.shark"] = false,
            ["toggle.auto.bisento.v2"] = false,
            ["toggle.auto.buy.bait"] = false,
            ["toggle.auto.buy.chip.law"] = false,
            ["toggle.auto.collect.fruit"] = false,
            ["toggle.auto.tween.to.fruit"] = false,
            ["toggle.auto.complete.quest"] = false,
            ["toggle.auto.drop.fruit"] = false,
            ["toggle.auto.factory.raid"] = false,
            ["toggle.auto.farm.bone"] = false,
            ["toggle.auto.farm.boss"] = false,
            ["toggle.auto.farm.cake.prince"] = false,
            ["toggle.auto.farm.chest"] = false,
            ["toggle.auto.farm.dough.king"] = false,
            ["toggle.auto.farm.ectoplasm"] = false,
            ["toggle.auto.farm.elite"] = false,
            ["toggle.auto.farm.elite.hop.server"] = false,
            ["toggle.auto.farm.island"] = false,
            ["toggle.auto.farm.materials"] = false,
            ["toggle.auto.farm.nearest"] = false,
            ["toggle.auto.farm.tyrant.of.the.skies"] = false,
            ["toggle.auto.fishing"] = false,
            ["toggle.auto.get.bazooka"] = false,
            ["toggle.auto.get.coat"] = false,
            ["toggle.auto.get.cool.shades"] = false,
            ["toggle.auto.get.magma.blaster"] = false,
            ["toggle.auto.get.marine.cap"] = false,
            ["toggle.auto.get.saber"] = false,
            ["toggle.auto.get.shark.saw"] = false,
            ["toggle.auto.get.trident"] = false,
            ["toggle.auto.get.usoap.s.hat"] = false,
            ["toggle.auto.get.wardens.sword"] = false,
            ["toggle.auto.hop.dough.king"] = false,
            ["toggle.auto.pirate.raid"] = false,
            ["toggle.auto.pray.gravestone"] = false,
            ["toggle.auto.quest.fishing"] = false,
            ["toggle.auto.raid.law"] = false,
            ["toggle.auto.random.bone"] = false,
            ["toggle.auto.random.fruit"] = false,
            ["toggle.auto.sell.fish"] = false,
            ["toggle.auto.soul.reaper"] = false,
            ["toggle.auto.spam.skill.z"] = false,
            ["toggle.auto.start.law"] = false,
            ["toggle.auto.store.fruit"] = false,
            ["toggle.auto.summon.boss"] = false,
            ["toggle.auto.summon.cake.prince"] = false,
            ["toggle.auto.travel"] = false,
            ["toggle.auto.try.luck.gravestone"] = false,
            ["toggle.auto.unlock.dough.dungeon"] = false,
            ["toggle.auto.unlock.phoenix.dungeon"] = false,
            ["toggle.bring.mob"] = true,
            ["toggle.esp.berry"] = false,
            ["toggle.fast.attack.buddha"] = false,
            ["toggle.fighting.style.auto.darkstep"] = false,
            ["toggle.fighting.style.auto.deathstep"] = false,
            ["toggle.fighting.style.auto.dragonbreath"] = false,
            ["toggle.fighting.style.auto.dragontalon"] = false,
            ["toggle.fighting.style.auto.electric"] = false,
            ["toggle.fighting.style.auto.electricclaw"] = false,
            ["toggle.fighting.style.auto.godhuman"] = false,
            ["toggle.fighting.style.auto.sanguine"] = false,
            ["toggle.fighting.style.auto.sharkman"] = false,
            ["toggle.fighting.style.auto.superhuman"] = false,
            ["toggle.fighting.style.auto.waterkungfu"] = false,
            ["toggle.fighting.style.use.darkstep"] = false,
            ["toggle.fighting.style.use.deathstep"] = false,
            ["toggle.fighting.style.use.dragonbreath"] = false,
            ["toggle.fighting.style.use.dragontalon"] = false,
            ["toggle.fighting.style.use.electric"] = false,
            ["toggle.fighting.style.use.electricclaw"] = false,
            ["toggle.fighting.style.use.godhuman"] = false,
            ["toggle.fighting.style.use.sanguine"] = false,
            ["toggle.fighting.style.use.sharkman"] = false,
            ["toggle.fighting.style.use.superhuman"] = false,
            ["toggle.fighting.style.use.waterkungfu"] = false,
            ["toggle.teleport.to.npc"] = false,
            ["toggle.teleport.to.player"] = false,
            ["toggle.turn.on.rtx.mode"] = false,
            ["toggle.unlock.zoom.limit"] = false,
        },
        OptionDefaults = {
            ["option.farm.nearest.max.distance"] = 1200,
            ["option.select.material"] = false,
            ["option.choose.boat"] = false,
            ["option.choose.sea.level"] = false,
            ["option.select.haki.states"] = false,
        },
        LegacyBindings = {
            ["global.AcientOne"] = {Id="toggle.auto.train.v4", Binding="global", Flag="AcientOne" },
            ["global.AutoBigmom"] = {Id="toggle.auto.get.buddy.sword", Binding="global", Flag="AutoBigmom" },
            ["global.AutoEcBoss"] = {Id="toggle.auto.get.midnight.blade", Binding="global", Flag="AutoEcBoss" },
            ["global.AutoHopServer"] = {Id="toggle.auto.hop.every.30.minutes", Binding="global", Flag="AutoHopServer" },
            ["global.AutoKenVTWO"] = {Id="toggle.auto.haki.observation.v2", Binding="global", Flag="AutoKenVTWO" },
            ["global.AutoKilo"] = {Id="toggle.auto.get.lei.accessory", Binding="global", Flag="AutoKilo" },
            ["global.AutoMatSoul"] = {Id="toggle.auto.farm.materials.skull.guitar", Binding="global", Flag="AutoMatSoul" },
            ["global.AutoRipIngay"] = {Id="toggle.auto.farm.rip.indra", Binding="global", Flag="AutoRipIngay" },
            ["global.AutoSerpentBow"] = {Id="toggle.auto.get.serpent.bow", Binding="global", Flag="AutoSerpentBow" },
            ["global.AutoTridentW2"] = {Id="toggle.auto.get.dragon.trident", Binding="global", Flag="AutoTridentW2" },
            ["global.AutoUnHaki"] = {Id="toggle.auto.three.color.haki", Binding="global", Flag="AutoUnHaki" },
            ["global.Auto_Cavender"] = {Id="toggle.auto.get.florentino.sword", Binding="global", Flag="Auto_Cavender" },
            ["global.Auto_Def_DarkCoat"] = {Id="toggle.auto.farm.darkbeard", Binding="global", Flag="Auto_Def_DarkCoat" },
            ["global.Auto_Rainbow_Haki"] = {Id="toggle.auto.haki.rainbow", Binding="global", Flag="Auto_Rainbow_Haki" },
            ["global.Auto_Soul_Guitar"] = {Id="toggle.auto.get.skull.guitar", Binding="global", Flag="Auto_Soul_Guitar" },
            ["global.Auto_SwanGG"] = {Id="toggle.auto.get.swan.glasses", Binding="global", Flag="Auto_SwanGG" },
            ["global.Auto_Tushita"] = {Id="toggle.auto.get.tushita", Binding="global", Flag="Auto_Tushita" },
            ["global.Auto_Yama"] = {Id="toggle.auto.get.yama", Binding="global", Flag="Auto_Yama" },
            ["global.AutofindKitIs"] = {Id="toggle.auto.find.kitsune.island", Binding="global", Flag="AutofindKitIs" },
            ["global.Bartilo_Quest"] = {Id="toggle.auto.complete.quest.bartilo", Binding="global", Flag="Bartilo_Quest" },
            ["global.BlackSpikey"] = {Id="toggle.auto.get.black.spikey", Binding="global", Flag="BlackSpikey" },
            ["global.BuyDrago"] = {Id="toggle.swap.draco.race", Binding="global", Flag="BuyDrago" },
            ["global.Bypass"] = {Id="toggle.turn.on.bypass.teleport", Binding="global", Flag="Bypass" },
            ["global.FastTravel"] = {Id="toggle.turn.on.fast.travel", Binding="global", Flag="FastTravel" },
            ["global.CDK"] = {Id="toggle.auto.get.cdk", Binding="global", Flag="CDK" },
            ["global.CDK_TS"] = {Id="toggle.auto.quest.tushita.cdk", Binding="global", Flag="CDK_TS" },
            ["global.CDK_YM"] = {Id="toggle.auto.quest.yama.cdk", Binding="global", Flag="CDK_YM" },
            ["global.CitizenQuest"] = {Id="toggle.auto.complete.quest.citizen", Binding="global", Flag="CitizenQuest" },
            ["global.Collect_Ember"] = {Id="toggle.auto.collect.azure.ember", Binding="global", Flag="Collect_Ember" },
            ["global.Complete_Trials"] = {Id="toggle.auto.complete.trial.race", Binding="global", Flag="Complete_Trials" },
            ["global.CraftVM"] = {Id="toggle.auto.craft.volcanic.magnet", Binding="global", Flag="CraftVM" },
            ["global.DT_Uzoth"] = {Id="toggle.upgrade.dragon.talon.v3", Binding="global", Flag="DT_Uzoth" },
            ["global.DarkBladev3"] = {Id="toggle.auto.dark.blade.v3", Binding="global", Flag="DarkBladev3" },
            ["global.Defeating"] = {Id="toggle.auto.kill.player.after.trial", Binding="global", Flag="Defeating" },
            ["global.Dojoo"] = {Id="toggle.auto.dojo.trainer", Binding="global", Flag="Dojoo" },
            ["global.DragoV1"] = {Id="toggle.auto.draco.v1", Binding="global", Flag="DragoV1" },
            ["global.DummyMan"] = {Id="toggle.auto.farm.training.dummy", Binding="global", Flag="DummyMan" },
            ["global.FarmBlazeEM"] = {Id="toggle.auto.dragon.hunter", Binding="global", Flag="FarmBlazeEM" },
            ["global.FrozenTP"] = {Id="toggle.auto.teleport.frozen.dimension", Binding="global", Flag="FrozenTP" },
            ["global.GetQFast"] = {Id="toggle.get.quest.haki.rainbow", Binding="global", Flag="GetQFast" },
            ["global.IceBossRen"] = {Id="toggle.auto.get.rengoku.sword", Binding="global", Flag="IceBossRen" },
            ["global.KeysRen"] = {Id="toggle.auto.get.key.rengoku", Binding="global", Flag="KeysRen" },
            ["global.Leviathan1"] = {Id="toggle.auto.attack.leviathan", Binding="global", Flag="Leviathan1" },
            ["global.LongsWord"] = {Id="toggle.auto.get.long.sword", Binding="global", Flag="LongsWord" },
            ["global.Lver"] = {Id="toggle.auto.pull.lever", Binding="global", Flag="Lver" },
            ["global.Prehis_DB"] = {Id="toggle.auto.collect.bones", Binding="global", Flag="Prehis_DB" },
            ["global.RaceClickAutov3"] = {Id="toggle.auto.turn.on.v3", Binding="global", Flag="RaceClickAutov3" },
            ["global.RaceClickAutov4"] = {Id="toggle.auto.turn.on.v4", Binding="global", Flag="RaceClickAutov4" },
            ["global.Relic123"] = {Id="toggle.auto.relic.draco.trial.v4", Binding="global", Flag="Relic123" },
            ["global.ResetPH"] = {Id="toggle.auto.reset.when.complete", Binding="global", Flag="ResetPH" },
            ["global.Safemode"] = {Id="toggle.panic.mode", Binding="global", Flag="Safemode" },
            ["global.SailBoat_Hydra"] = {Id="toggle.auto.drive.to.hydra.island", Binding="global", Flag="SailBoat_Hydra" },
            ["global.TPDoor"] = {Id="toggle.auto.teleport.to.race.doors", Binding="global", Flag="TPDoor" },
            ["global.TpDrago_Prehis"] = {Id="toggle.tween.to.draco.trial.v4", Binding="global", Flag="TpDrago_Prehis" },
            ["global.Tp_LgS"] = {Id="toggle.tween.to.legendary.sword.seller.npc", Binding="global", Flag="Tp_LgS" },
            ["global.Trade_Ember"] = {Id="toggle.auto.trade.azure.ember", Binding="global", Flag="Trade_Ember" },
            ["global.TrainDrago"] = {Id="toggle.auto.train.draco.v4", Binding="global", Flag="TrainDrago" },
            ["global.TwinHook"] = {Id="toggle.auto.get.twin.hooks", Binding="global", Flag="TwinHook" },
            ["global.UPGDrago"] = {Id="toggle.tween.to.upgrade.draco.trial", Binding="global", Flag="UPGDrago" },
            ["global.WalkWater"] = {Id="toggle.turn.on.ice.walk", Binding="global", Flag="WalkWater" },
            ["global.daylightN"] = {Id="toggle.turn.on.time", Binding="global", Flag="daylightN" },
            ["global.obsFarm"] = {Id="toggle.auto.farm.haki.observation", Binding="global", Flag="obsFarm" },
            ["global.tweenShrine"] = {Id="toggle.auto.shrine.actived", Binding="global", Flag="tweenShrine" },
            ["lease.Auto_Awakener"] = {Id="toggle.auto.awakening", Binding="lease", Flag="Auto_Awakener" },
            ["lease.FishBoat"] = {Id="toggle.auto.attack.fish.boat", Binding="lease", Flag="FishBoat" },
            ["lease.HCM"] = {Id="toggle.auto.attack.haunted.crew.member", Binding="lease", Flag="HCM" },
            ["lease.KillAuraFull"] = {Id="toggle.kill.aura", Binding="lease", Flag="KillAuraFull" },
            ["lease.MobCrew"] = {Id="toggle.auto.attack.fish.crew.member", Binding="lease", Flag="MobCrew" },
            ["lease.PGB"] = {Id="toggle.auto.attack.pirate.ship", Binding="lease", Flag="PGB" },
            ["lease.Piranha"] = {Id="toggle.auto.kill.piranha", Binding="lease", Flag="Piranha" },
            ["lease.Prehis_DE"] = {Id="toggle.auto.collect.dragon.egg", Binding="lease", Flag="Prehis_DE" },
            ["lease.Prehis_Find"] = {Id="toggle.auto.find.prehistoric.island", Binding="lease", Flag="Prehis_Find" },
            ["lease.Prehis_Skills"] = {Id="toggle.auto.start.event", Binding="lease", Flag="Prehis_Skills" },
            ["lease.Raiding"] = {Id="toggle.auto.raid.safe", Binding="lease", Flag="Raiding" },
            ["lease.SailBoats"] = {Id="toggle.auto.sail.sit.down.and.turn.on", Binding="lease", Flag="SailBoats" },
            ["lease.SeaBeast1"] = {Id="toggle.auto.attack.sea.beast", Binding="lease", Flag="SeaBeast1" },
            ["lease.Shark"] = {Id="toggle.auto.kill.shark", Binding="lease", Flag="Shark" },
            ["lease.TerrorShark"] = {Id="toggle.auto.kill.terror.shark", Binding="lease", Flag="TerrorShark" },
        },
        ControlRuntimeOwners = {
            ["toggle.auto.farm.nearest"] = {"farm.nearest"},
            ["toggle.auto.farm.island"] = {"farm.island"},
            ["toggle.auto.factory.raid"] = {"farm.factory"},
            ["toggle.auto.farm.ectoplasm"] = {"farm.ectoplasm"},
            ["toggle.auto.farm.elite"] = {"farm.elite"},
            ["toggle.auto.farm.elite.hop.server"] = {"farm.elite_hop"},
            ["toggle.auto.farm.cake.prince"] = {"farm.cake_prince"},
            ["toggle.auto.summon.cake.prince"] = {"farm.cake_summon"},
            ["toggle.auto.farm.dough.king"] = {"farm.dough_king"},
            ["toggle.auto.hop.dough.king"] = {"farm.dough_hop"},
            ["toggle.auto.unlock.dough.dungeon"] = {"farm.unlock_dough"},
            ["toggle.auto.unlock.phoenix.dungeon"] = {"farm.unlock_phoenix"},
            ["toggle.auto.farm.bone"] = {"farm.bones"},
            ["toggle.auto.soul.reaper"] = {"farm.soul_reaper"},
            ["toggle.auto.random.bone"] = {"farm.random_bone"},
            ["toggle.auto.try.luck.gravestone"] = {"farm.gravestone_luck"},
            ["toggle.auto.pray.gravestone"] = {"farm.gravestone_pray"},
            ["toggle.auto.farm.tyrant.of.the.skies"] = {"farm.tyrant"},
            ["toggle.auto.summon.boss"] = {"farm.tyrant_summon"},
            ["toggle.auto.farm.materials"] = {"farm.material"},
            ["toggle.auto.farm.boss"] = {"farm.boss"},
            ["toggle.auto.quest.sea.2"] = {"progress.second_sea"},
            ["toggle.auto.get.pole.v1"] = {"progress.pole_v1"},
            ["toggle.auto.pole.v2"] = {"progress.pole_v2"},
            ["toggle.auto.get.saber"] = {"progress.saber"},
            ["toggle.auto.get.usoap.s.hat"] = {"progress.usoap_hat"},
            ["toggle.auto.get.marine.cap"] = {"progress.marine_cap"},
            ["toggle.auto.teleport.barista.cousin"] = {"travel.barista_cousin"},
            ["toggle.auto.random.fruit"] = {"fruit.gacha"},
            ["toggle.auto.store.fruit"] = {"fruit.inventory"},
            ["toggle.auto.collect.fruit"] = {"fruit.spawned"},
            ["toggle.auto.travel"] = {"travel.island"},
            ["toggle.teleport.to.player"] = {"travel.player"},
            ["toggle.teleport.to.npc"] = {"travel.npc"},
            ["toggle.auto.attack.fish.boat"] = {"legacy.sea.combat"},
            ["toggle.auto.attack.fish.crew.member"] = {"legacy.sea.combat"},
            ["toggle.auto.attack.haunted.crew.member"] = {"legacy.sea.combat"},
            ["toggle.auto.attack.leviathan"] = {"legacy.sea.combat"},
            ["toggle.auto.attack.pirate.ship"] = {"legacy.sea.combat"},
            ["toggle.auto.attack.sea.beast"] = {"legacy.sea.combat"},
            ["toggle.auto.awakening"] = {"legacy.auto_awakener.12446"},
            ["toggle.auto.collect.azure.ember"] = {"legacy.collect_ember.12064"},
            ["toggle.auto.collect.bones"] = {"legacy.prehis_db.11658"},
            ["toggle.auto.collect.dragon.egg"] = {"legacy.prehis_de.11678"},
            ["toggle.auto.collect.gear"] = {"mirage.blue_gear"},
            ["toggle.auto.collect.mirage.chest"] = {"mirage.chest"},
            ["toggle.auto.complete.quest.bartilo"] = {"progress.bartilo"},
            ["toggle.auto.complete.quest.citizen"] = {"legacy.citizenquest.9409"},
            ["toggle.auto.complete.trial.race"] = {"legacy.race.complete_trials"},
            ["toggle.auto.craft.volcanic.magnet"] = {"legacy.craftvm.11476"},
            ["toggle.auto.dark.blade.v3"] = {"legacy.quest.dark_blade_v3"},
            ["toggle.auto.dojo.trainer"] = {"legacy.drago.dojo"},
            ["toggle.auto.draco.v1"] = {"legacy.drago.v1"},
            ["toggle.auto.draco.v2"] = {"progress.race.draco.v2"},
            ["toggle.auto.draco.v3"] = {"progress.race.draco.v3"},
            ["toggle.auto.dragon.hunter"] = {"legacy.farmblazeem"},
            ["toggle.auto.drive.to.hydra.island"] = {"legacy.sailboat_hydra.11777"},
            ["toggle.auto.farm.darkbeard"] = {"legacy.quest.darkbeard"},
            ["toggle.auto.farm.haki.observation"] = {"legacy.obsfarm"},
            ["toggle.auto.farm.materials.skull.guitar"] = {"legacy.automatsoul.10589"},
            ["toggle.auto.farm.rip.indra"] = {"legacy.autoripingay.9490"},
            ["toggle.auto.farm.training.dummy"] = {"legacy.dummyman.9456"},
            ["toggle.auto.find.kitsune.island"] = {"legacy.autofindkitis.11998"},
            ["toggle.auto.find.mirage.island"] = {"mirage.find"},
            ["toggle.auto.find.prehistoric.island"] = {"legacy.prehis_find.11510"},
            ["toggle.auto.get.black.spikey"] = {"legacy.blackspikey.8811"},
            ["toggle.auto.get.buddy.sword"] = {"legacy.autobigmom.8978"},
            ["toggle.auto.get.cdk"] = {"legacy.cdk.8091"},
            ["toggle.auto.get.dragon.trident"] = {"legacy.autotridentw2.8773"},
            ["toggle.auto.get.florentino.sword"] = {"legacy.auto_cavender.8997"},
            ["toggle.auto.get.key.rengoku"] = {"legacy.keysren.8749"},
            ["toggle.auto.get.lei.accessory"] = {"legacy.autokilo.9053"},
            ["toggle.auto.get.long.sword"] = {"legacy.longsword.8792"},
            ["toggle.auto.get.midnight.blade"] = {"legacy.autoecboss.8856"},
            ["toggle.auto.get.rengoku.sword"] = {"legacy.icebossren.8730"},
            ["toggle.auto.get.serpent.bow"] = {"legacy.autoserpentbow.9036"},
            ["toggle.auto.get.skull.guitar"] = {"legacy.auto_soul_guitar.10472"},
            ["toggle.auto.get.swan.glasses"] = {"legacy.auto_swangg.8954"},
            ["toggle.auto.get.tushita"] = {"legacy.auto_tushita.7997"},
            ["toggle.auto.get.twin.hooks"] = {"legacy.twinhook.9016"},
            ["toggle.auto.get.yama"] = {"legacy.auto_yama.8036"},
            ["toggle.auto.haki.observation.v2"] = {"legacy.autokenvtwo.9258"},
            ["toggle.auto.haki.rainbow"] = {"legacy.auto_rainbow_haki.9101"},
            ["toggle.auto.hop.every.30.minutes"] = {"legacy.settings.auto_hop"},
            ["toggle.auto.kill.piranha"] = {"legacy.sea.combat"},
            ["toggle.auto.kill.player.after.trial"] = {"legacy.defeating.11045"},
            ["toggle.auto.kill.shark"] = {"legacy.sea.combat"},
            ["toggle.auto.kill.terror.shark"] = {"legacy.sea.combat"},
            ["toggle.auto.look.at.moon"] = {"legacy.race.look_moon"},
            ["toggle.auto.pull.lever"] = {"legacy.lver.10860"},
            ["toggle.auto.quest.sea.3"] = {"progress.third_sea"},
            ["toggle.auto.quest.tushita.cdk"] = {"legacy.cdk.tushita"},
            ["toggle.auto.quest.yama.cdk"] = {"legacy.cdk.yama.main"},
            ["toggle.auto.relic.draco.trial.v4"] = {"legacy.relic123.11340"},
            ["toggle.auto.reset.when.complete"] = {"legacy.resetph.11694"},
            ["toggle.auto.sail.sit.down.and.turn.on"] = {"legacy.sea.sail"},
            ["toggle.auto.shrine.actived"] = {"legacy.tweenshrine.12037"},
            ["toggle.auto.start.event"] = {"legacy.prehis_skills.11585"},
            ["toggle.auto.teleport.frozen.dimension"] = {"legacy.frozentp.11761"},
            ["toggle.auto.teleport.to.race.doors"] = {"legacy.tpdoor.10924"},
            ["toggle.auto.three.color.haki"] = {"legacy.autounhaki.9523"},
            ["toggle.auto.trade.azure.ember"] = {"legacy.trade_ember.12085"},
            ["toggle.auto.tween.to.fruit"] = {"fruit.tween"},
            ["toggle.auto.train.draco.v4"] = {"legacy.traindrago.11370"},
            ["toggle.auto.train.v4"] = {"legacy.acientone.10878"},
            ["toggle.auto.turn.on.haki"] = {"legacy.settings.auto_haki"},
            ["toggle.auto.turn.on.v3"] = {"legacy.raceclickautov3.7099"},
            ["toggle.auto.turn.on.v4"] = {"legacy.raceclickautov4.7118"},
            ["toggle.auto.tween.to.advanced.fruit.dealer"] = {"travel.advanced_fruit_dealer"},
            ["toggle.auto.unlock.donswan"] = {"quest.don_swan_unlock"},
            ["toggle.auto.race.v2"] = {"progress.race.v2"},
            ["toggle.auto.race.v3"] = {"progress.race.v3"},
            ["toggle.auto.get.ghoul.race"] = {"progress.race.ghoul"},
            ["toggle.auto.get.cyborg.race"] = {"progress.race.cyborg"},
            ["toggle.auto.use.skill.z.buddha"] = {"legacy.settings.auto_buddha"},
            ["toggle.change.transparency.can.see"] = {"mirage.visibility"},
            ["toggle.disable.notify"] = {"legacy.settings.disable_notify"},
            ["toggle.kill.aura"] = {"legacy.combat.kill_aura"},
            ["toggle.panic.mode"] = {"legacy.safemode.7150"},
            ["toggle.remove.hit"] = {"legacy.destroyhit.7184"},
            ["toggle.stats.auto_blox_fruit"] = {"legacy.auto_devilfruit.7601"},
            ["toggle.stats.auto_defense"] = {"legacy.auto_defense.7615"},
            ["toggle.stats.auto_gun"] = {"legacy.auto_gun.7587"},
            ["toggle.stats.auto_melee"] = {"legacy.auto_melee.7558"},
            ["toggle.stats.auto_sword"] = {"legacy.auto_sword.7573"},
            ["toggle.swap.draco.race"] = {"legacy.buydrago.11413"},
            ["toggle.turn.on.ice.walk"] = {"legacy.walkwater.14293"},
            ["toggle.tween.to.draco.trial.v4"] = {"legacy.tpdrago_prehis.11398"},
            ["toggle.tween.to.legendary.sword.seller.npc"] = {"legacy.tp_lgs.8394"},
            ["toggle.tween.to.mirage.island"] = {"mirage.highest"},
            ["toggle.tween.to.upgrade.draco.trial"] = {"legacy.upgdrago.11234"},
            ["toggle.upgrade.dragon.talon.v3"] = {"legacy.dt_uzoth.11435"},
        },
    },
    UI = {
        -- Canonical presentation aliases are shared by Core telemetry and ui.lua.
        -- Keep this mapping as the single source of truth when visual domains move.
        PresentationTabAliases = {
            Home="Main", Settings="System", Utilities="System", Misc="System", Combat="Combat",
            Fruit="Items", Fruits="Items", Quest="Progress", Quests="Progress", Progression="Progress", Race="Race",
            Sea="Events", Events="Events", Mirage="Events", SeaEvent="Events", Prehistoric="Events",
            Raid="Raids", Raids="Raids", Teleport="Travel", Travel="Travel", Items="Shop",
        },
        -- Status/telemetry providers created by legacy domains can feed more than one
        -- new presentation domain. The active-tab bridge therefore uses sets instead
        -- of forcing split UI domains back into one alias.
        PresentationActivityMap = {
            Home={Main=true}, Settings={System=true,Combat=true,Travel=true,Progress=true}, Items={Items=true,Shop=true,Progress=true},
            Progress={Progress=true,Race=true}, World={Events=true,Travel=true}, Raid={Raids=true},
        },
        Timing = { FocusFlashDuration = 0.55, OwnershipRefreshDelay = 0.45, OwnershipStatusClearDelay = 1.10, HostResolveTimeout = 5.0 },
        Notification = {
            QueueLimit = 20,
            DefaultCooldown = 1.0, DefaultDuration = 3.0, InfoDuration = 2.5, ShortDuration = 2.0,
            PurchaseCooldown = 0.8, PurchaseDuration = 2.4, StyleActionDuration = 2.8, StyleEquipDuration = 2.6,
            RaceSeaBeastCooldown = 10.0, RaidStateCooldown = 5.0, LoadedCooldown = 5.0, RedeemCooldown = 2.0,
        },
    },

    Player = {
        Movement = {
            -- Defaults are fallback display values only. Core does not write them to the
            -- Humanoid until the user explicitly changes the corresponding slider.
            WalkSpeed = {Default = 30, Min = 0, Max = 300},
            JumpPower = {Default = 50, Min = 0, Max = 500},
        },
    },
    Stats = {
        Upgrade = {Default = 10, Min = 0, Max = 1000, Step = 1},
    },

    Localization = {
        Default = "vi",
        Fallback = "en",
        ManifestDelay = 2.0,
        Languages = {
            vi = "Tiếng Việt",
            en = "English",
            th = "ไทย",
            id = "Bahasa Indonesia",
        },
    },

    Release = {
        HubInfoSchema = 1,
        HubInfo = { CopyDepthLimit = 6, DefaultTextLimit = 300, UrlLimit = 260, MaxChangelogEntries = 50, HomeChangelogEntries = 8 },
    },
}

-- Backward-compatible identity aliases are derived from this same table; there is
-- no secondary metadata authority.
Config.Metadata = Config.App
Config.HubName = Config.App.HubName
Config.Version = Config.App.Version
Config.Revision = Config.App.Revision
Config.BuildName = Config.App.BuildName
Config.DisplayVersion = Config.App.DisplayVersion
-- Derived alias: UI artifact identity has one authority in Source.Artifacts.
Config.Release.UpdatedAt = Config.App.UpdatedAt
Config.Release.UIStamp = Config.Source.Artifacts.UI
Config.ReleaseStamp = Config.Source.Artifacts.Config
return Config
